//
//  ElementsList.swift
//  VitaMi
//
//  Created by Иван Маришин on 04.07.2021.
//

import Foundation

struct Element: Identifiable {
    let id = UUID()
    let name: String
    let elementInfo: String?
    let productInfo: String?
    let normalValue: [String: Array<Double>]?
    let symptomsLowValue: Set<String>?
    let symptomsHighValue: Set<String>?
    let helper: Set<String>?
    let blocker: Set<String>?
    
    static func getElementsList() -> [Element] {
        [
            Element(name: "Fe",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mkmol/l":[8.95, 30.43]],
                    symptomsLowValue: [
                        "headache",
                        "dizziness",
                        "fatigue",
                        "irritability",
                        "pallor of skin",
                        "cold intolerance",
                        "memory impairment",
                        "deformation and fragility of nails",
                        "decreased appetite",
                        "dry skin",
                        "bad dream",
                        "edemas",
                        "skin numbness",
                    ],
                    symptomsHighValue: [],
                    helper: ["B2", "B6", "B9", "Cu"],
                    blocker: ["Ca", "P", "Zn"]),
            Element(name: "K",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[3.50, 5.50]],
                    symptomsLowValue: [
                        "muscle pain",
                        "muscle spasm",
                        "fatigue",
                        "depression",
                        "dry skin",
                        "hair loss and brittleness",
                        "thirst",
                        "acne",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Ca",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[2.15, 2,50]],
                    symptomsLowValue: [
                        "muscle spasm",
                        "muscle pain",
                        "fatigue",
                        "bone pain",
                        "frequent bruising",
                        "bone fractures",
                        "joint pain",
                        "skin numbness",
                        "abdominal pain",
                    ],
                    symptomsHighValue: [],
                    helper: ["D"],
                    blocker: ["P", "Mg", "Fe"]),
            Element(name: "Mg",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[0.60, 0.95]],
                    symptomsLowValue: [
                        "fatigue",
                        "irritability",
                        "decreased appetite",
                        "muscle spasm",
                        "muscle pain",
                        "bad dream",
                        "abdominal pain",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: ["Ca"]),
            Element(name: "Cu",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mkmol/l":[11.00, 24.00]],
                    symptomsLowValue: [
                        "headache",
                        "dizziness",
                        "fatigue",
                        "frequent colds",
                        "pallor of skin",
                        "bone pain",
                        "joint pain",
                        "bone fractures",
                        "fading hair",
                        "decreased visual acuity",
                    ],
                    symptomsHighValue: [],
                    helper: ["Fe"],
                    blocker: ["C"]),
            Element(name: "Na",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[135.00, 147.00]],
                    symptomsLowValue: [
                        "muscle spasm",
                        "headache",
                        "acne",
                        "decreased appetite",
                        "edemas",
                        "dermatitis",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "P",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[0.80, 1.50]],
                    symptomsLowValue: [
                        "fatigue",
                        "frequent colds",
                        "muscle pain",
                        "frequent bruising",
                        "bone pain",
                        "depression",
                        "irritability",
                        "memory impairment",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: ["Ca"]),
            Element(name: "Zn",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mkmol/l":[9.20, 20.00]],
                    symptomsLowValue: [
                        "bad dream",
                        "decreased visual acuity",
                        "fatigue",
                        "irritability",
                        "depression",
                        "decreased appetite",
                        "deformation and fragility of nails",
                        "white spots on the nails",
                        "dry skin",
                        "hair loss and brittleness",
                        "fading hair",
                        "acne",
                        "dermatitis",
                        "abdominal pain",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: ["Cu", "Ca", "Fe"]),
            Element(name: "Vitanim B1",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "skin numbness",
                        "memory impairment",
                        "decreased visual acuity",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitanim B2",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "dry skin",
                        "deformation and fragility of nails",
                        "hair loss and brittleness",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitanim PP",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "decreased appetite",
                        "fatigue",
                        "irritability",
                        "memory impairment",
                        "dermatitis",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitanim B5",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "dermatitis",
                        "deformation and fragility of nails",
                        "hair loss and brittleness",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitamin B6",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "irritability",
                        "dermatitis",
                        "skin numbness",
                        "edemas",
                        "pallor of skin",
                        "fatigue",
                        "dizziness",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitanim B9",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "pallor of skin",
                        "fatigue",
                        "dizziness",
                        "dry skin",
                        "frequent colds",
                        "abdominal pain",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitanim B12",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "pallor of skin",
                        "fatigue",
                        "dizziness",
                        "skin numbness",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitamin C",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "frequent colds",
                        "fatigue",
                        "edemas",
                        "pallor of skin",
                        "fatigue",
                        "dizziness",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitanim P",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "frequent bruising",
                        "bleeding gums",
                        "joint pain",
                        "bone pain",
                        "fatigue",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitamin A",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "decreased appetite",
                        "dry skin",
                        "joint pain",
                        "headache",
                        "bone fractures",
                        "hair loss and brittleness",
                        "deformation and fragility of nails",
                        "decreased visual acuity",
                    ],
                    symptomsHighValue: [],
                    helper: ["E", "C"],
                    blocker: []),
            Element(name: "Vitamin D",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "muscle spasm",
                        "muscle pain",
                        "fatigue",
                        "bone pain",
                        "frequent bruising",
                        "bone fractures",
                        "joint pain",
                        "skin numbness",
                        "abdominal pain",
                    ],
                    symptomsHighValue: [],
                    helper: ["Ca"],
                    blocker: []),
            Element(name: "Vitamin E",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "pallor of skin",
                        "fatigue",
                        "dizziness",
                        "skin numbness",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
            Element(name: "Vitamin F",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    symptomsLowValue: [
                        "acne",
                        "dermatitis",
                        "hair loss and brittleness",
                        "frequent colds",
                        "dry skin",
                        "abdominal pain",
                    ],
                    symptomsHighValue: [],
                    helper: [],
                    blocker: []),
        ]
    }
}
