//
//  ElementsList.swift
//  VitaMi
//
//  Created by Иван Маришин on 04.07.2021.
//

import Foundation

struct Element: Identifiable {
    let id = UUID()
    let symbol: String
    let enName: String
    let ruName: String
    let type: String
    let elementInfo: String
    let productInfo: String
    let normalValue: [String: Array<Double>]
    let helper: Array<String>
    let blocker: Array<String>
    
    static func getElementsList() -> [Element] {
        [
            Element(symbol: "Fe",
                    enName: "Iron",
                    ruName: "Железо",
                    type: "Microelement",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mkmol/l":[8.95, 30.43]],
                    helper: ["Vitamin B2", "Vitamin B6", "Vitamin B9", "Cu"],
                    blocker: ["Ca", "P", "Zn"]),
            Element(symbol: "K",
                    enName: "Potassium",
                    ruName: "Калий",
                    type: "Microelement",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[3.50, 5.50]],
                    helper: [],
                    blocker: []),
            Element(symbol: "Ca",
                    enName: "Calcium",
                    ruName: "Кальций",
                    type: "Microelement",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[2.15, 2,50]],
                    helper: ["Vitamin D"],
                    blocker: ["P", "Mg", "Fe"]),
            Element(symbol: "Mg",
                    enName: "Magnesium",
                    ruName: "Магний",
                    type: "Microelement",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[0.60, 0.95]],
                    helper: [],
                    blocker: ["Ca"]),
            Element(symbol: "Cu",
                    enName: "Copper",
                    ruName: "Медь",
                    type: "Microelement",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mkmol/l":[11.00, 24.00]],
                    helper: ["Fe"],
                    blocker: ["Vitamin C"]),
            Element(symbol: "Na",
                    enName: "Sodium",
                    ruName: "Натрий",
                    type: "Microelement",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[135.00, 147.00]],
                    helper: [],
                    blocker: []),
            Element(symbol: "P",
                    enName: "Phosphorus",
                    ruName: "Фосфор",
                    type: "Microelement",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mmol/l":[0.80, 1.50]],
                    helper: [],
                    blocker: ["Ca"]),
            Element(symbol: "Zn",
                    enName: "Zinc",
                    ruName: "Цинк",
                    type: "Microelement",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: ["mkmol/l":[9.20, 20.00]],
                    helper: [],
                    blocker: ["Cu", "Ca", "Fe"]),
            Element(symbol: "Vitanim B1",
                    enName: "Vitanim B1",
                    ruName: "Витамин B1",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: [],
                    blocker: []),
            Element(symbol: "Vitanim B2",
                    enName: "Vitanim B2",
                    ruName: "Витамин B2",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: ["Fe"],
                    blocker: []),
            Element(symbol: "Vitanim PP",
                    enName: "Vitanim PP",
                    ruName: "Витамин PP",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: [],
                    blocker: []),
            Element(symbol: "Vitanim B5",
                    enName: "Vitanim B5",
                    ruName: "Витамин B5",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: [],
                    blocker: []),
            Element(symbol: "Vitamin B6",
                    enName: "Vitamin B6",
                    ruName: "Витамин B6",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: ["Fe"],
                    blocker: []),
            Element(symbol: "Vitanim B9",
                    enName: "Vitanim B9",
                    ruName: "Витамин B9",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: ["Fe"],
                    blocker: []),
            Element(symbol: "Vitanim B12",
                    enName: "Vitanim B12",
                    ruName: "Витамин B12",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: [],
                    blocker: []),
            Element(symbol: "Vitamin C",
                    enName: "Vitamin C",
                    ruName: "Витамин C",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: ["Vitamin A"],
                    blocker: ["Cu"]),
            Element(symbol: "Vitanim P",
                    enName: "Vitanim P",
                    ruName: "Витамин P",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: [],
                    blocker: []),
            Element(symbol: "Vitamin A",
                    enName: "Vitamin A",
                    ruName: "Витамин A",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: ["Vitamin E", "Vitamin C"],
                    blocker: []),
            Element(symbol: "Vitamin D",
                    enName: "Vitamin D",
                    ruName: "Витамин D",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: ["Ca"],
                    blocker: []),
            Element(symbol: "Vitamin E",
                    enName: "Vitamin E",
                    ruName: "Витамин E",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: ["Vitamin A"],
                    blocker: []),
            Element(symbol: "Vitamin F",
                    enName: "Vitamin F",
                    ruName: "Витамин F",
                    type: "Vitamin",
                    elementInfo: "",
                    productInfo: "",
                    normalValue: [:],
                    helper: [],
                    blocker: []),
        ]
    }
}
